#!/usr/bin/env python3
"""Generate the documents from templates and measurements. No document holds a typed number.

  python3 scripts/render.py           # write README.md, JOURNAL.md and REPORT.md
  python3 scripts/render.py --check   # fail if any of them differs from what would be written

`docs/templates/*.md` hold the prose. Everything factual is a placeholder:

  {{name}}          one value, resolved by scripts/facts.py from a file some script measured
  {{block:name}}    a generated section -- a table, a list of figures, a per-database breakdown

Substitution is strict in both directions. A placeholder with no matching fact is an error, not an
empty string, so a template cannot quietly reference something that stopped being measured. A fact
with no measurement behind it renders as a visible marker rather than a blank or a stale value, so
a document produced from an unfinished run says which numbers it is waiting for.

`--check` regenerates into memory and compares. It is the replacement for the old practice of
pinning hand-written numbers to measurements after the fact: there is nothing to pin, because there
is nothing hand-written. If a document on disk disagrees with the evidence, `make check` fails.
"""
import argparse, difflib, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import facts as facts_mod  # noqa: E402
from common import ROOT  # noqa: E402

TEMPLATES = os.path.join(ROOT, "docs", "templates")
PLACEHOLDER = re.compile(r"\{\{([a-z_]+:)?([A-Za-z0-9_.]+)\}\}")
GENERATED_NOTE = ("<!-- Generated by scripts/render.py from docs/templates/{name} and the files in\n"
                  "     build/. Do not edit this file: `make docs` overwrites it, and every number\n"
                  "     in it comes from a measurement rather than from anyone's memory. -->\n")


def blocks():
    """Generated sections, each a function of the measurements.

    Kept in one registry so a template can only reach content that some script produces. Tables come
    from report.py, which already knows how to lay the measurements out."""
    import report, report_pairs

    def guarded(fn, need="results"):
        def run():
            data = facts_mod.load(need)
            if not data:
                return (f"*No `build/{facts_mod.SOURCES[need]}` yet, so this section has nothing to "
                        f"show. It is written by the run, not by hand.*")
            try:
                return fn(data)
            except Exception as exc:                              # noqa: BLE001
                return f"*This section could not be built from the measurements: {exc}*"
        return run

    return {
        "summary_table": guarded(lambda r: report.summary_table(report.rows(r))),
        "dolt_report": guarded(lambda r: embed_report(r)),
        "index_policy": guarded(lambda r: demote(report.policy_section(report.rows(r))
                                                 or "*Neither index policy has been measured yet.*")),
        "index_parity": guarded(lambda r: "\n".join(report.index_parity_table(report.rows(r)))
                                or "*No mode has been measured for index parity yet.*"),
        "environment": guarded(lambda r: report.environment_table(), need="environment"),
        "machine_sharing": guarded(lambda e: report.sharing_caveat(e), need="environment"),
        "memory_table": guarded(lambda m: memory_table(m), need="memory"),
        "missing_facts": lambda: missing_list(),
        # the two further pairs (scripts/report_pairs.py)
        "versions": lambda: report_pairs.versions_table(),
        "pg_pair_table": guarded(lambda r: report_pairs.pair_table(r, "pg")),
        "lite_pair_table": guarded(lambda r: report_pairs.pair_table(r, "lite")),
        "pg_pair_inline": guarded(lambda r: report_pairs.inline_table(r, "pg")),
        "lite_pair_inline": guarded(lambda r: report_pairs.inline_table(r, "lite")),
        "pair_refusals": guarded(lambda r: report_pairs.refusals(r)),
        "pg_pair_memory": guarded(lambda r: report_pairs.memory_table(r, "pg")),
        "lite_pair_memory": guarded(lambda r: report_pairs.memory_table(r, "lite")),
        "pair_memory_study": lambda: report_pairs.memory_study_table(),
        "memory_grid": guarded(lambda r: report_pairs.memory_grid(r)),
        "databases": guarded(lambda r: report_pairs.databases_table(r)),
        "sizes_note": guarded(lambda r: report_pairs.sizes_note(r)),
        "findings_disk": guarded(lambda r: report_pairs.findings_totals(r, "bytes")),
        "findings_time": guarded(lambda r: report_pairs.findings_totals(r, "seconds")),
        "sizes_all": guarded(lambda r: report_pairs.sizes_all(r, "bytes")),
        "times_all": guarded(lambda r: report_pairs.sizes_all(r, "seconds")),
        "refusals_summary": guarded(lambda r: report_pairs.refusals_summary(r)),
    }


def embed_report(r):
    """The MySQL/Dolt report, generated as it always was, placed under a heading of REPORT.md's own:
    its file header, human note, machine table and index-policy section go, since REPORT.md carries
    each once already."""
    import report
    report.RAW = r
    text = report.report(report.rows(r))
    text = text.replace(report.GENERATED, "").replace(report.HUMAN_NOTE, "")
    for heading in ("## The machine\n", "## What maintaining the indexes costs\n"):   # each carried once already
        a = text.find(heading)
        if a < 0:          # the report writes the index section only once a policy has been measured
            continue
        b = text.find("\n## ", a + 1)
        text = text[:a] + (text[b + 1:] if b >= 0 else "")
    return demote_all(text)


def demote_all(text):
    """A whole generated document placed under a heading of the template's own: its H1 goes, every
    H2 becomes an H3 and every H3 an H4."""
    out = []
    for l in text.split("\n"):
        if l.startswith("# "):
            continue
        out.append("#" + l if l.startswith("## ") or l.startswith("### ") else l)
    return "\n".join(out).strip("\n")


def demote(text):
    """A block that carries its own top-level heading, placed under a heading of the README's own:
    the block's H2 goes, and its H3s become H4s, so the README's structure is the template's."""
    lines = [l for l in text.split("\n")]
    out = []
    for k, l in enumerate(lines):
        if k < 2 and l.startswith("## "):
            continue
        out.append("#" + l if l.startswith("### ") else l)
    return "\n".join(out).lstrip("\n")


def memory_table(memory):
    """What each database needs to open, in each stored form: same rows, different history."""
    from common import human
    one, rc = memory.get("oneshot") or {}, memory.get("rowcommit") or {}
    dbs = sorted(set(one) | set(rc),
                 key=lambda d: -((rc.get(d) or one.get(d) or {}).get("rows") or 0))
    if not dbs:
        return "*No memory measurements yet.*"
    L = ["| database | rows | Dolt store with 3 commits:<br>memory to open it | Dolt store with one commit per row:<br>memory to open it | commits in that store | that store on disk |",
         "|---|---:|---:|---:|---:|---:|"]
    for d in dbs:
        o, r = one.get(d) or {}, rc.get(d) or {}
        rows = o.get("rows") or r.get("rows")
        commits = r.get("commits")
        L.append(f"| `{d}` "
                 f"| {rows:,} " if rows else f"| `{d}` | ? "
                 )
        L[-1] += (f"| {fmt_mb(o.get('megabytes'))} "
                  f"| {fmt_mb(r.get('megabytes'))} "
                  f"| {f'{commits:,}' if commits else 'not readable'} "
                  f"| {human(r['disk_bytes']) if r.get('disk_bytes') else '?'} |")
    return "\n".join(L)


def fmt_mb(v):
    from common import human_mb
    return human_mb(v) if v else "over the ladder"


def missing_list():
    f = facts_mod.build()
    gaps = f.missing()
    if not gaps:
        return "*Every number in this document is backed by a measurement.*"
    return ("The following are not measured yet, and appear in this document as "
            f"`{facts_mod.MISSING}`:\n\n"
            + "\n".join(f"* `{g}` — from {f.sources[g]}" for g in gaps))


def render(name, text, f, reg):
    unknown = []

    def sub(m):
        kind, key = m.group(1), m.group(2)
        if kind == "block:":
            if key not in reg:
                unknown.append(f"block:{key}")
                return m.group(0)
            return reg[key]()
        if key not in f:
            unknown.append(key)
            return m.group(0)
        return f[key]

    body = PLACEHOLDER.sub(sub, text)
    if unknown:
        raise SystemExit(f"{name}: template refers to {len(unknown)} name(s) nothing produces: "
                         + ", ".join(sorted(set(unknown))))
    return GENERATED_NOTE.format(name=name) + "\n" + body


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="do not write; fail if a document differs from what would be written")
    a = ap.parse_args()

    if not os.path.isdir(TEMPLATES):
        sys.exit(f"no templates in {os.path.relpath(TEMPLATES, ROOT)}")
    f = facts_mod.build()
    reg = blocks()
    stale, wrote = [], []
    for name in sorted(os.listdir(TEMPLATES)):
        if not name.endswith(".md"):
            continue
        text = open(os.path.join(TEMPLATES, name), encoding="utf-8").read()
        out = render(name, text, f, reg)
        dest = os.path.join(ROOT, name)
        current = open(dest, encoding="utf-8").read() if os.path.exists(dest) else None
        if a.check:
            if current != out:
                stale.append((name, current or "", out))
            continue
        if current != out:
            open(dest, "w", encoding="utf-8").write(out)
            wrote.append(name)

    if a.check:
        for name, current, out in stale:
            diff = list(difflib.unified_diff(current.splitlines(), out.splitlines(),
                                             f"{name} on disk", f"{name} from measurements",
                                             lineterm="", n=1))
            print(f"  x {name} is not what the measurements produce:")
            for line in diff[:14]:
                print(f"      {line}")
        if stale:
            print(f"\n  {len(stale)} document(s) stale; `make docs` regenerates them")
            return 1
        print("  every document matches the measurements")
        return 0

    for name in wrote:
        print(f"  . wrote {name}")
    if not wrote:
        print("  documents already match the measurements")
    gaps = f.missing()
    if gaps:
        print(f"  ! {len(gaps)} fact(s) have no measurement and render as "
              f"{facts_mod.MISSING}; `python3 scripts/facts.py --missing` lists them")
    return 0


if __name__ == "__main__":
    sys.exit(main())
